### ISSUE TITLE
Imroving Use Cases

### ISSUE THREAD

**Issue by TM-GIT-HUB** [ec-jrc/lisflood-usecases#5]
I would like to report 2 options for improving the value of the UseCases:
 
1) It seems that the currently provided use cases can not be used in a "straight foreward" way. In case of the ETRS89_UseCase the path information in the settings files is not in line with the pathes the different inputs are stored in. While the settings files can of course be easily adjusted, new users might benefit from use cases that can be used "as is".

2) The projection information in the case of ETRS89_UseCase is no longer stored in all netCDF maps. As a result, LISFLOOD raises the error: "miscInitial.py", line 196, in initial raise Exception("If using projected coordinates (x, y), a variable with the 'proj4_params' "
Exception: If using projected coordinates (x, y), a variable with the 'proj4_params' attribute must be included in the precipitation file or in settings file!"

THANKS FOR ALL YOUR ENDEAVOURS!!!

**Comment by TM-GIT-HUB** [comment]
Ad 2): seems like including the projection information in the settings does not help, seems to be a requirement in the projected precip data, although the expetion says:

Exception: If using projected coordinates (x, y), a variable with the 'proj4_params' attribute must be included in the precipitation file or in settings file!

**Comment by domeniconappo** [comment]
Hi @TM-GIT-HUB 
the setting is included: https://github.com/ec-jrc/lisflood-usecases/search?q=proj4_params&unscoped_q=proj4_params

In the code, LF reads that option in case precip nc file does not include the projection variable.
Did you try to run second usecase and still get the error?

Also 1) seems strange to me. I will test them again and fix it.
Thanks for reporting!
d

**Comment by TM-GIT-HUB** [comment]
Hi Domenico,

Thanks for your comment! Yes, it is included in the PreRun, but not in the Run-Settings... But you are right that it still may work if correctly specified in the settings, I forgot to also include it in the LFBINDING section - my bad, I will test... I will include it in the meteo input as well as it will do no harm there...

Thanks!!!
